### ISSUE TITLE
安装 kratosx 失败

### ISSUE THREAD

**Issue by sycute** [limes-cloud/kratosx#2]
按照文档说明执行 go install github.com/limes-cloud/kratosx/cmd/kratosx@latest 命令出现如下提示：

go: github.com/limes-cloud/kratosx/cmd/kratosx@latest: module github.com/limes-cloud/kratosx@latest found (v1.0.26), but does not contain package github.com/limes-cloud/kratosx/cmd/kratosx

**Comment by limes-cloud** [comment]
github.com/limes-cloud/kratosx/cmd/kratosx 的cli 工具还没写完，目前代码还未提交上来，kratosx主要就是拉取 limes-cloud代码仓库中的layout模板，使用go-kratos的命令一样可以正常拉取，当然kratosx后续想接入一些一键curd等功能，期待你也一起贡献代码

**Comment by sycute** [comment]
使用 kratos new verse-nft -r git@github.com:limes-cloud/kratos-layout.git 替代
